# Generated by Django 4.2.4 on 2023-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model1',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Time', models.DateTimeField()),
                ('Joining_Year', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Weight', models.FloatField()),
                ('About_you', models.TextField()),
                ('Your_website_link', models.URLField()),
                ('Upload_your_photo', models.FileField(upload_to='files/')),
                ('Video_duration', models.DurationField()),
                ('Agree', models.BooleanField()),
            ],
        ),
    ]
